# Generated by Django 4.2.1 on 2023-05-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.FileField(blank=True, null=True, upload_to='files/')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Other', 'Other')], max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('maiden_name', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('number_of_dependants', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single Never Married', 'Single Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Engaged', 'Engaged')], max_length=100)),
                ('dob', models.DateField()),
                ('country_of_birth', models.CharField(max_length=100)),
                ('national_id_no', models.CharField(max_length=12)),
                ('residence_status', models.CharField(choices=[('Yes residing in Zimbabwe', 'Yes residing in Zimbabwe'), ('No residing in another country', 'No residing in another country')], max_length=100)),
                ('current_citizenship', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.IntegerField()),
                ('home_telephone', models.IntegerField(blank=True, null=True)),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKinDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Other', 'Other')], max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('maiden_name', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('address', models.TextField()),
                ('national_id_no', models.CharField(max_length=12)),
                ('relationship', models.CharField(max_length=100)),
                ('employer', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('dob', models.DateField()),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin_details', to='Applicant.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Other', 'Other')], max_length=100)),
                ('loan_purpose', models.CharField(max_length=200)),
                ('disbursement_option', models.CharField(choices=[('Bank Account', 'Bank Account'), ('EcoCash', 'Eco Cash'), ('Others', 'Others')], max_length=100)),
                ('existing_loan_amount', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_tenure', models.CharField(choices=[('6 months', '6 months'), ('12 months', '12 months'), ('24 months', '24 months')], max_length=100)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='Applicant.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('employer_tel_no', models.IntegerField(blank=True, null=True)),
                ('employer_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_number', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('expiry_of_employment', models.CharField(max_length=100)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_details', to='Applicant.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Cession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_cessions', to='Applicant.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('bank_branch_code', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_no', models.IntegerField()),
                ('account_type', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='Applicant.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented'), ('Stay with Parents', 'Stay with Parents')], max_length=100)),
                ('address', models.TextField()),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('years_at_curent_res', models.IntegerField()),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to='Applicant.applicant')),
            ],
        ),
    ]
