# Generated by Django 4.2.1 on 2023-05-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='addressdetails',
            name='years_at_curent_res',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='country_of_birth',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='current_citizenship',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='home_telephone',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='maiden_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='number_of_dependants',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='residence_status',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='bank_branch_code',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='employer_address',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='employer_contact_person',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='employer_tel_no',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='expiry_of_employment',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='employmentdetails',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='nextofkindetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nextofkindetails',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='nextofkindetails',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='nextofkindetails',
            name='maiden_name',
        ),
        migrations.RemoveField(
            model_name='nextofkindetails',
            name='profession',
        ),
    ]
