# Generated by Django 4.2.1 on 2023-05-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0003_applicant_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.AddField(
            model_name='loandetails',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='Applicant.applicant'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='loan_purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='loan_tenure',
            field=models.CharField(choices=[('3 months', '3 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('24 months', '24 months')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Cession',
        ),
        migrations.AddField(
            model_name='loandetails',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_loans', to='Applicant.product'),
            preserve_default=False,
        ),
    ]
