# Generated by Django 4.2.1 on 2023-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0004_product_loandetails_has_confirmed_loandetails_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='monthly_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='national_id',
            field=models.FileField(blank=True, null=True, upload_to='files/national_id/'),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='payslip',
            field=models.FileField(blank=True, null=True, upload_to='files/payslip/'),
        ),
    ]
