# Generated by Django 4.1.9 on 2023-06-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
        ('Applicant', '0006_alter_loandetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_loans', to='Agent.agent'),
        ),
    ]
